# gradle 로 만든 yml사용시
spring:
    application:
        name: ls2life
    profiles:
        active: local
    thymeleaf:
        mode: HTML
        encoding: UTF-8
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
        cache: false

    # DataSource 자동구성 설정
    datasource:
        # jdbc driver name
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://150.230.255.58:3306/dbplayground"
        username: dbplaygroundmaster
        password: dbpgmaster

    jpa:
        # 접속할 database 설정
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                # none 동작 없음.
                # create-only: table이 없을 경우 create함.
                # drop: table을 drop.
                # creat: 기존 table 존재시 table drop후 create.
                # create-drop: App 실행시 table create. App 종료시 table drop.
                # validate: Entity 설정과 기존 table 설정이 다르면 Error 발생.
                # update: table, column의 정보가 달라졌을 경우 추가.
                auto: update
        # App 시작시 @Entity 테이블의 create문 실행. 시작시마다 초기화.
        generate-ddl: false
        # template view 화면의 렌더링이 끝날때까지 Lazy fetch 가능
        open-in-view: false
server:
    port: 8080
# 기존 application.properties 사용시 하기의 내용처럼 사용.

# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.url=jdbc:mysql://150.230.255.58:3306/dbplayground
# spring.datasource.username=dbplaygroundmaster
# spring.datasource.password=dbpgmaster
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost/dbplayground
#spring.datasource.username=dbplaygroundmaster
#spring.datasource.password=dbpgmaster
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.mvc.view.prefix=
# spring.mvc.view.suffix=.jsp

# dbplayground
# dbplaygroundmaster
# dbpgmaster

# xml 사용시
# <?xml version="1.0" encoding="UTF-8"?>
# <beans xmlns="http://www.springframework.org/schema/beans"
#    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
#    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
#    <bean id="userBean" class="kr.or.connect.diexam01.UserBean"></bean>

# </beans>
