
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dbplayground
        username: dbplaygroundmaster
        password: dbpgmaster
    jpa:
        open-in-view: true
        database: mysql
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show-sql: true
                format-sql: true
                use-sql-comments: true
logging:
    level:
        root: info
    logback:
        rollingpolicy:
            max-history: 30
            max-file-size: 100MB
            file-name-pattern: ${LOG_FILE},%d{yyyy-MM-dd}-%i.log
    file:
        name: logs/homepage.log
    pattern:
        dateformat: yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul
